### ISSUE TITLE
Can this model test image in wild?

### ISSUE THREAD

**Issue by FinallyKiKi** [ZiyiZhang27/Dite-HRNet#1]

**Comment by mornfairy** [comment]
I want to know too.

**Comment by ZiyiZhang27** [comment]
Hi! We haven't tried our model on images in wild. In theory, to achieve better detection performance in wild, you should make some adjustments to the training data. And to perform realtime detection, perhaps you can refer to the live demo in this repo: [https://github.com/stefanopini/simple-HRNet#running-the-live-demo](https://github.com/stefanopini/simple-HRNet#running-the-live-demo).
