### ISSUE TITLE
可以提供一下预训练模型吗？谢谢!

### ISSUE THREAD

**Issue by zstuli** [ZiyiZhang27/Dite-HRNet#3]

**Comment by ZiyiZhang27** [comment]
Hi~感谢您对本工作的关注！
All checkpoint files here: https://drive.google.com/drive/folders/1_unL2XMll5vL1_zstnm3EC9BVFr_jrsf?usp=sharing
为了匹配论文中的模块名称，我们在后期对代码中某些类进行了改名，所以一小部分的模型文件可能无法使用了，如果接下来有时间的话我们会对这部分模型进行重新训练~

**Comment by zstuli** [comment]
感谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ZiyiZhang27/Dite-HRNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月26日(星期四) 上午9:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ZiyiZhang27/Dite-HRNet] 可以提供一下预训练模型吗？谢谢! (Issue #3)





 
Hi感谢您对本工作的关注！
 All checkpoint files here: https://drive.google.com/drive/folders/1_unL2XMll5vL1_zstnm3EC9BVFr_jrsf?usp=sharing
 为了匹配论文中的模块名称，我们在后期对代码中某些类进行了改名，所以一小部分的模型文件可能无法使用了，如果接下来有时间的话我们会对这部分模型进行重新训练
